import React, { useEffect, useRef, useState } from 'react';
import { Activity, ArrowUpRight, BrainCircuit, ChevronRight, CircleHelp, Factory, Gauge, GitBranch, LayoutDashboard, Pause, Play, Radio, RefreshCw, ShieldCheck, SlidersHorizontal, Sparkles, Target, Timer, Zap } from 'lucide-react';
import { stationGraph, zoneColors } from './twin-core/stationGraph';
import { advanceTwin, createTwinSnapshot, createTwinStore } from './store/digitalTwinStore';
import { compareActions, explain, projectAction } from './decide/decisionEngine';

const tabs = [{ id: 'operations', label: 'Operations', icon: LayoutDashboard }, { id: 'investigation', label: 'Investigation', icon: GitBranch }, { id: 'management', label: 'Management', icon: Gauge }];
const fmt = (value) => `${Math.round(value * 100)}%`;

function Header({ active, setActive, tick, isPlaying, speed, onToggle, onSpeed, onReset }) { return <header className="topbar"><div className="brand"><div className="brand-mark"><Factory size={18} /></div><div><strong>DIGITAL TWIN</strong><span>Plant intelligence / live prototype</span></div></div><nav>{tabs.map(({ id, label, icon: Icon }) => <button className={active === id ? 'tab active' : 'tab'} onClick={() => setActive(id)} key={id}><Icon size={16} />{label}</button>)}</nav><div className="live"><span className={`live-dot ${isPlaying ? '' : 'paused'}`} />{isPlaying ? 'LIVE' : 'PAUSED'} <small>tick {String(tick).padStart(3, '0')}</small></div><div className="header-controls"><button title={isPlaying ? 'Pause simulation' : 'Resume simulation'} onClick={onToggle}>{isPlaying ? <Pause size={14} /> : <Play size={14} />}</button><button onClick={onSpeed}>{speed}x</button><button title="Reset simulation" onClick={onReset}><RefreshCw size={14} /></button></div></header> }

function Metric({ label, value, note, accent = '' }) { const normalizedNote = note.replace('ranked by confidence × impact', 'ranked by risk × confidence × impact'); return <div className="metric"><span>{label}</span><strong className={accent}>{value}</strong><small>{normalizedNote}</small></div> }
function Confidence({ value }) { return <span className={`confidence ${value < .5 ? 'low' : ''}`}><span />{fmt(value)} confidence</span> }

function PriorityQueue({ predictions, selected, onSelect }) { return <section className="panel queue-panel"><div className="panel-title"><div><span className="eyebrow">ASSESS / PRIORITY QUEUE</span><h2>What needs attention</h2></div><span className="formula">risk × confidence × impact</span></div><div className="queue-list">{predictions.map((prediction) => <button className={`queue-row ${selected?.id === prediction.id ? 'selected' : ''}`} key={prediction.id} onClick={() => onSelect(prediction)}><span className="rank">0{prediction.rank}</span><span className="station"><b>{prediction.stationId}</b><small>{prediction.type} signal</small></span><span className="risk"><b>{fmt(prediction.risk)}</b><small>raw risk</small></span><span className="score"><b>{fmt(prediction.priorityScore)}</b><small>priority</small></span><ChevronRight size={16} /></button>)}</div></section> }

function StationMap({ simulation }) { return <section className="panel map-panel"><div className="panel-title"><div><span className="eyebrow">TWIN CORE / STATION GRAPH</span><h2>Factory pulse</h2></div><span className="signal"><Radio size={14} /> {Object.keys(simulation).length} stations connected</span></div><div className="map"><div className="flow-line" />{stationGraph.map((station, index) => { const state = simulation[station.id]; const hot = state?.status === 'critical' || state?.status === 'watch'; return <div className={`station-node ${hot ? 'hot' : ''}`} style={{ left: `${7 + (index % 7) * 14}%`, top: `${28 + Math.floor(index / 7) * 38}%`, '--zone': zoneColors[station.zone] }} key={station.id}><span className="node-core">{station.id}</span><small>{state?.status ?? 'nominal'}</small></div> })}</div><div className="legend"><span><i className="dot material" />Material flow</span><span><i className="dot assembly" />Assembly</span><span><i className="dot quality" />Quality</span><span><i className="dot warning" />Active signal</span></div></section> }

function DecisionPanel({ prediction }) { const actions = compareActions(prediction); const [chosen, setChosen] = useState(actions.find((a) => a.recommended)); const projected = projectAction(chosen); return <section className="panel decision-panel"><div className="panel-title"><div><span className="eyebrow">DECIDE / RECOMMENDATION</span><h2>Act with context</h2></div><Sparkles size={18} color="#f3b562" /></div><div className="decision-lead"><div className="ai-orb"><BrainCircuit size={24} /></div><div><b>Prioritize {prediction.stationId} intervention</b><p>Full instrumentation makes this a stronger decision than the higher-risk S11 alert.</p></div></div><div className="actions">{actions.map((action) => <button className={`action ${chosen.id === action.id ? 'chosen' : ''}`} onClick={() => setChosen(action)} key={action.id}><span className="action-id">{action.id}</span><span><b>{action.label}</b>{action.recommended && <small className="recommendation">★ Recommended</small>}<small>{action.estimatedCost} cost · {action.riskReduction} risk reduction</small></span><strong>{action.estimatedEffectPct > 0 ? '+' : ''}{action.estimatedEffectPct}%</strong></button>)}</div><div className="projection"><div><span>COUNTERFACTUAL SIM</span><b>Projected throughput (% of baseline target)</b></div><div className="projection-values"><strong>{projected.before}%</strong><ArrowUpRight size={16} /><strong className="up">{projected.after}%</strong></div></div><button className="primary"><Zap size={15} /> Simulate action <span>↗</span></button></section> }

function Operations({ snapshot, selected, setSelected }) { const selectedPrediction = selected ?? snapshot.predictions[0]; const s2 = snapshot.simulation.S2; const measuredCount = snapshot.signals.filter((signal) => signal.measured).length; return <><div className="hero"><div><span className="eyebrow">OPERATIONS VIEW / SHIFT A</span><h1>See the signal<br /><em>behind the noise.</em></h1><p>Digital Twin turns incomplete factory data into a decision your team can act on.</p></div><div className="hero-status"><Activity size={16} /><span>System health</span><strong>{(100 - (s2.status === 'critical' ? 9 : 5)).toFixed(1)}%</strong><small>updated at tick {snapshot.tick} · {measuredCount}/14 measured</small></div></div><div className="metric-strip"><Metric label="Throughput" value={`${Math.max(0, 94 - Math.round(s2.queueDepth / 8))}%`} note={`target 94% · queue ${s2.queueDepth}`} /><Metric label="Open predictions" value={String(snapshot.predictions.length).padStart(2, '0')} note="ranked by confidence × impact" accent="orange" /><Metric label="Mean lead time" value={`${Math.round(12 + s2.cycleTime / 6)}m`} note={`cycle time ${s2.cycleTime}s at S2`} /><Metric label="Data coverage" value={`${Math.round(measuredCount / stationGraph.length * 100)}%`} note="soft sensing active" accent="teal" /></div><div className="main-grid"><div><PriorityQueue predictions={snapshot.predictions} selected={selectedPrediction} onSelect={setSelected} /><StationMap simulation={snapshot.simulation} /><section className="panel event-panel"><div className="panel-title"><div><span className="eyebrow">UNDERSTAND / EVENT STREAM</span><h2>What just changed</h2></div><span className="signal"><Timer size={14} /> every 4 seconds</span></div><div className="event-list">{snapshot.eventLog.map((event) => <div key={event}><span className="live-dot" />{event}</div>)}</div></section></div><div><section className="panel why-panel"><div className="panel-title"><div><span className="eyebrow">WHY THIS RANKS HERE</span><h2>{selectedPrediction.stationId} / {selectedPrediction.type}</h2></div><CircleHelp size={17} /></div>{explain(selectedPrediction).map((item) => <div className="contribution" key={item.label}><div className="contribution-top"><span>{item.label}</span><b>{fmt(item.value)}</b></div><div className="bar"><i style={{ width: `${item.value * 100}%` }} /></div><small>{item.note}</small></div>)}<div className="signal-note"><SlidersHorizontal size={15} /> S11 is partially observed and inferred from its neighbors.</div></section><DecisionPanel prediction={selectedPrediction} /></div></div></> }

function Investigation({ snapshot }) { return <><div className="hero compact"><div><span className="eyebrow">INVESTIGATION VIEW / CAUSAL TRACE</span><h1>Follow the <em>evidence.</em></h1><p>Trace the hidden relationship between the feeder, weld cell, and downstream quality.</p></div><button className="secondary"><RefreshCw size={15} /> Re-run trace</button></div><div className="investigation-grid"><section className="panel genealogy"><div className="panel-title"><div><span className="eyebrow">GENEALOGY STORE</span><h2>Candidate causes for S13 quality event</h2></div><span className="tag">2 upstream paths found</span></div>{[['S11', 'Robot feeder', 82, 'Inferred'], ['S3', 'Torque cell', 41, 'Partial']].map(([id, name, value, source]) => <div className="cause" key={id}><div className="cause-icon" style={{ '--zone': zoneColors[stationGraph.find((s) => s.id === id).zone] }}>{id}</div><div className="cause-info"><b>{name}</b><small>{source} signal · upstream neighbor</small><div className="bar"><i style={{ width: `${value}%` }} /></div></div><strong>{value}%</strong></div>)}</section><section className="panel trace"><div className="panel-title"><div><span className="eyebrow">SIGNAL HISTORY</span><h2>Divergence detected</h2></div></div><div className="chart"><div className="chart-grid" /> <svg viewBox="0 0 600 190" preserveAspectRatio="none"><path d="M0 135 C70 130 80 110 150 120 S230 96 290 112 S370 90 430 72 S520 66 600 48" /><path className="muted-line" d="M0 145 C70 144 90 136 160 140 S240 133 300 138 S390 130 450 136 S540 128 600 131" /></svg><span className="chart-label l1">S2 · measured</span><span className="chart-label l2">S11 · inferred</span></div><div className="trace-note"><Target size={16} /><span><b>Confidence gap: 53 points</b> is driving the ranking divergence.</span></div></section></div></> }

function Management({ snapshot }) { return <><div className="hero compact"><div><span className="eyebrow">MANAGEMENT VIEW / MODEL HEALTH</span><h1>Trust that <em>learns.</em></h1><p>Outcomes feed back into confidence, making the next decision more useful than the last.</p></div><span className="last-updated">Updated just now</span></div><div className="management-grid"><section className="panel learning-card"><div className="panel-title"><div><span className="eyebrow">LEARN / LIVE METRICS</span><h2>Model performance</h2></div><ShieldCheck size={20} color="#78d6c5" /></div><div className="big-metric"><strong>{fmt(snapshot.metrics.precision)}</strong><span>precision</span><small>+6.2 pts over 7 days</small></div><div className="metric-bars"><div><span>False-alert rate <b>{fmt(snapshot.metrics.falseAlertRate)}</b></span><div className="bar"><i className="red" style={{ width: '8%' }} /></div></div><div><span>Lead time <b>{snapshot.metrics.avgLeadTimeMinutes} min</b></span><div className="bar"><i className="teal" style={{ width: '73%' }} /></div></div></div></section><section className="panel outcome-card"><div className="panel-title"><div><span className="eyebrow">OUTCOME VALIDATOR</span><h2>Last resolved signals</h2></div></div>{[['S2', 'True positive', 'Resolved in 14m', 'true'], ['S11', 'False alert', 'No quality impact', 'false'], ['S6', 'True positive', 'Resolved in 22m', 'true']].map(([id, title, note, state]) => <div className="outcome" key={id}><span className={`outcome-state ${state}`}>{state === 'true' ? '✓' : '×'}</span><span><b>{id} · {title}</b><small>{note}</small></span><span className="outcome-time">today</span></div>)}</section></div></> }

export default function App() { const [active, setActive] = useState('operations'); const [tick, setTick] = useState(0); const [speed, setSpeed] = useState(1); const [isPlaying, setIsPlaying] = useState(true); const twinStore = useRef(createTwinStore(0)); const [snapshot, setSnapshot] = useState(() => createTwinSnapshot(twinStore.current, 0)); const [selected, setSelected] = useState(null); useEffect(() => { if (!isPlaying) return undefined; const timer = setInterval(() => setTick((value) => value + 1), Math.max(500, 4000 / speed)); return () => clearInterval(timer); }, [isPlaying, speed]); useEffect(() => { twinStore.current = advanceTwin(twinStore.current, tick); setSnapshot(createTwinSnapshot(twinStore.current, tick)); }, [tick]); const reset = () => { twinStore.current = createTwinStore(0); setTick(0); setSelected(null); setIsPlaying(true); }; const cycleSpeed = () => setSpeed((value) => value === 1 ? 2 : value === 2 ? 4 : 1); return <div className="app-shell"><Header active={active} setActive={setActive} tick={tick} isPlaying={isPlaying} speed={speed} onToggle={() => setIsPlaying((value) => !value)} onSpeed={cycleSpeed} onReset={reset} /><main>{active === 'operations' && <Operations snapshot={snapshot} selected={selected} setSelected={setSelected} />}{active === 'investigation' && <Investigation snapshot={snapshot} />}{active === 'management' && <Management snapshot={snapshot} />}</main><footer><span><span className="live-dot" /> Digital Twin core operational</span><span>UNDERSTAND → ASSESS → DECIDE → LEARN</span><span>Prototype / simulated production history</span></footer></div> }
